include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    use_key_in_widget_constructors: ignore

linter:
  rules:
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    avoid_unnecessary_containers: true
    sort_child_properties_last: true
    always_use_package_imports: true
    prefer_single_quotes: true
